// Writes tool/whiteboard.lock.json, the exact set of npm packages tool/build_whiteboard.dart downloads
// to bundle the whiteboard (app/excalidraw/bridge.js), from an npm package-lock.json (v2/v3).
//
// It takes the transitive closure of the roots below (dependencies, optional and peer dependencies,
// resolved the way Node does: nearest node_modules/ first, then up the tree), keeping each package at
// the node_modules/ path npm gave it, plus esbuild's native binary for each host platform we build on.
// Platform-only packages (an `os` or `cpu` field, like fsevents) are left out: nothing in the browser
// bundle imports them.
//
// Only needed when bumping Excalidraw, React or esbuild. In a scratch directory:
//   npm init -y && npm install --package-lock-only @excalidraw/excalidraw@<v> react@18 react-dom@18 esbuild@<v>
//   dart run tool/gen_whiteboard_lock.dart <scratch>/package-lock.json
// (run from the repo root; the output path can be given as a second argument).
import 'dart:convert';
import 'dart:io';

/// What bridge.js imports (react-dom/client is react-dom).
const roots = ['@excalidraw/excalidraw', 'react', 'react-dom'];

/// The hosts esbuild's binary is pinned for.
const platforms = ['linux-x64', 'linux-arm64', 'darwin-x64', 'darwin-arm64'];

void main(List<String> args) {
  final lockPath = args.isNotEmpty ? args[0] : 'package-lock.json';
  final outPath = args.length > 1 ? args[1] : 'tool/whiteboard.lock.json';
  final lock = jsonDecode(File(lockPath).readAsStringSync()) as Map<String, dynamic>;
  final packages = (lock['packages'] as Map).cast<String, dynamic>();

  /// Where Node would find [name] when required from the package at [from] ('' is the root).
  String? resolve(String from, String name) {
    var dir = from;
    while (true) {
      final candidate = dir.isEmpty ? 'node_modules/$name' : '$dir/node_modules/$name';
      if (packages.containsKey(candidate)) return candidate;
      if (dir.isEmpty) return null;
      final i = dir.lastIndexOf('/node_modules/');
      dir = i < 0 ? '' : dir.substring(0, i);
    }
  }

  final seen = <String>{};
  final queue = <String>[];
  for (final r in roots) {
    final p = resolve('', r) ?? (throw StateError('$r is not in $lockPath'));
    if (seen.add(p)) queue.add(p);
  }
  while (queue.isNotEmpty) {
    final path = queue.removeLast();
    final pkg = packages[path] as Map<String, dynamic>;
    final deps = <String>{
      ...((pkg['dependencies'] as Map?)?.keys.cast<String>() ?? const []),
      ...((pkg['optionalDependencies'] as Map?)?.keys.cast<String>() ?? const []),
      ...((pkg['peerDependencies'] as Map?)?.keys.cast<String>() ?? const []),
    };
    for (final d in deps) {
      final p = resolve(path, d);
      if (p == null) continue; // an optional or peer dependency npm didn't install
      final dp = packages[p] as Map<String, dynamic>;
      if (dp.containsKey('os') || dp.containsKey('cpu')) continue;
      if (seen.add(p)) queue.add(p);
    }
  }

  Map<String, Object?> entry(String path) {
    final p = packages[path] as Map<String, dynamic>;
    if (p['link'] == true) throw StateError('$path is a link, not a registry package');
    final name = p['name'] as String? ?? path.substring(path.lastIndexOf('node_modules/') + 'node_modules/'.length);
    return {
      'path': path,
      'name': name,
      'version': p['version'],
      'resolved': p['resolved'],
      'integrity': p['integrity'],
    };
  }

  final esbuildVersion = (packages['node_modules/esbuild'] as Map?)?['version'] ??
      (throw StateError('esbuild is not in $lockPath'));
  final out = {
    'comment': 'Generated by tool/gen_whiteboard_lock.dart; used by tool/build_whiteboard.dart. Do not edit.',
    'roots': roots,
    'esbuild': {
      'version': esbuildVersion,
      'platforms': {
        for (final pl in platforms) pl: entry('node_modules/@esbuild/$pl'),
      },
    },
    'packages': [for (final p in (seen.toList()..sort())) entry(p)],
  };
  File(outPath).writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(out)}\n');
  stdout.writeln('$outPath: ${seen.length} packages, esbuild $esbuildVersion');
}
